### ISSUE TITLE
error?  transPoseFwd   

### ISSUE THREAD

**Issue by maxpy** [zhusz/CVPR15-CFSS#1]
Error using transPoseFwd (line 14)
length(T) must be the same as size(oldPose,1)!

what's wrong?

**Comment by zhusz** [comment]
Not reproduced

**Comment by zhusz** [comment]
Never reproduced
Could you provide more details like the call stack info etc

**Comment by zhusz** [comment]
First, at my side I never observe such error and hence I cannot give explicit explanation to the problem.
Since I have received more than two bug reports on the same issue in function getTransViaMerge, I believe there might be something wrong in it. Currently I did some modification to the function and I believe the problem might be solved.

**Comment by maxpy** [comment]
Thank you to answer my question , I solve the problem with matlabpool;  
Thanks

**Comment by zhusz** [comment]
Yes! That is precisely the cause! Thank you very much for the discovery. 
The problem is due to our very old version of codes (without using parpool) that output row vector of transform objects rather than a column vector, a standard form we apply in our subsequent implementations. Hence, other functions would prompt error if they find the size of the first dim of transformation objects is not equal to the number of samples. 
Since we always use matlabpool enabled environment all later, we didn't find the problem until now.
So, to force all Ts in getTransViaMerge to be column vector seems to be the fastest way of solving the problem.
Sincerely thanks to your discovery!

**Comment by maxpy** [comment]
You're welcome.  BTW ,Thanks to your open source code. Great job!

**Comment by zhusz** [comment]
Thanks for you appreciation! :)
We are so glad to find that our codes can provide help to this area.
