### ISSUE TITLE
I cann't get the same  results as your paper

### ISSUE THREAD

**Issue by zbzoujianfa** [zhusz/CVPR15-CFSS#5]
I am not sure, I used the model which is offered by this web, but I can't get the result as your paper.
the variable 'er_abs' represents  the final error in your inferenceCFSS program, in this vector, from 1 to 330 represents the HELEN test results, the mean value is 13.7559, form 331 to 554 represents the LFPW test results, the mean value is 3.5879, and from 555 to 689 represents the IBUG test results, the mean value is 7.7492. I wonder to know why my results is not the same as yours. Thank you for your explanation.

**Comment by zhusz** [comment]
Please note that er_abs is the absolute error, for which the Helen dataset is of course large because all faces have large size. You should use the final normalized 'er' as the results as I stated in the readme part. This codes produce result within 0.1% fluctuation compared with the original reported results as verified by many other researchers. The only difference between this version and our original experiment version is that we use vl_feat here.

**Comment by zbzoujianfa** [comment]
Thank your for your explanation again!

**Comment by zbzoujianfa** [comment]
Thank your for your explanation again!

**Comment by zbzoujianfa** [comment]
Thank your for your explanation again!
